name: C++ Build and Test

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify Node.js version 16

      - name: Checkout Repository
        uses: actions/checkout@v2

      # Iterate through the chapters (Ch1, Ch2, etc.)
      - name: Build and Test Chapters
        run: |
          for chapter in Chapter/*; do
            if [ -d "$chapter" ]; then
              echo "Building and testing $chapter"
              cd "$chapter"
              for file in *.cpp; do
                if [ -f "$file" ]; then
                  g++ -o "${file%.*}" "$file"
                  "./${file%.*}"
                fi
              done
              cd ..
            fi
          done
